### ISSUE TITLE
Introducir URL del favicon manualmente

### ISSUE THREAD

**Issue by h1david96** [cherrera0001/ScriptsPython#2]
Hola, muchas gracias por tu código, me ayudó mucho.

Me gustaría proponerte un cambio en el código ya que no en todas las web el favicon.ico está ubicado en la misma ruta ni está en el mismo formato (.ico).

Sería bueno cambiar:
`favicon_url = f"http://{sys.argv[1]}/favicon.ico"`

Por:
`favicon_url = f"{sys.argv[1]}"`

Así sería posible introducir la url manualmente.

**Comment by cherrera0001** [comment]
Muchas gracias por tu aporte, se hace commit.
